Revert "Test under PyTest 7.0.x and 7.1.x"
This reverts commit bf8d9e89c6d6780a94cc5c724e6666118afa7322.

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -269,8 +269,6 @@ jobs:
           - salt~=3004.0
         pytest-version:
           - "~=6.2.0"
-          - "~=7.0.0"
-          - "~=7.1.0"
 
     steps:
     - uses: actions/checkout@v2
@@ -437,8 +435,6 @@ jobs:
           - salt~=3004.0
         pytest-version:
           - "~=6.2.0"
-          - "~=7.0.0"
-          - "~=7.1.0"
 
     steps:
     - uses: actions/checkout@v2
@@ -582,6 +578,169 @@ jobs:
         path: artifacts/runtests-*.log
 
 
+  Linux_3_5:
+    name: Linux-3.5
+    runs-on: ubuntu-20.04
+    needs: Pre-Commit
+
+    timeout-minutes: 25
+
+    strategy:
+      fail-fast: false
+      max-parallel: 4
+      matrix:
+        python-version:
+          - 3.5
+        salt-version:
+          - salt~=3003.0
+          - salt~=3004.0
+        pytest-version:
+          - "~=6.0.0"
+          - "~=6.1.0"
+
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    - name: Install Nox
+      run: |
+        python -m pip install --upgrade pip
+        pip install nox 'pytest${{ matrix.pytest-version }}'
+
+    - name: Gather CodeCov Info
+      if: always()
+      id: codecov-info
+      run: |
+        echo ::set-output name=flag-python-version::$(python -c "import sys; print('Py{}{}'.format(*sys.version_info))")
+        echo ::set-output name=flag-pytest-version::$(python -c "import pytest; print('PyTest{}{}'.format(*pytest.__version__.split('.')))")
+        echo ::set-output name=flag-salt-version::$(python -c "print('Salt{}'.format('_'.join(str(v) for v in '${{ matrix.salt-version }}'.split('==')[-1].split('.'))))")
+        echo ::set-output name=flag-runner-os::$(python -c "print('${{ runner.os }}'.replace('-latest', ''))")
+        echo ::set-output name=uploader-url::$(python -c "print('https://uploader.codecov.io/latest/codecov-linux')")
+
+    - name: Create CodeCov Flags
+      if: always()
+      id: codecov
+      run: |
+        echo ::set-output name=flags::$(python -c "print(','.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-salt-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")
+        echo ::set-output name=report-name::$(python -c "print('-'.join(['${{ steps.codecov-info.outputs.flag-runner-os }}', '${{ steps.codecov-info.outputs.flag-python-version }}', '${{ steps.codecov-info.outputs.flag-salt-version }}', '${{ steps.codecov-info.outputs.flag-pytest-version }}']))")
+
+    - name: Install Test Requirements
+      env:
+        SALT_REQUIREMENT: ${{ matrix.salt-version }}
+        PYTEST_VERSION_REQUIREMENT: pytest${{ matrix.pytest-version }}
+      run: |
+        nox --force-color -e tests-${{ matrix.python-version }} --install-only
+
+    - name: Test
+      id: run-tests
+      env:
+        SALT_REQUIREMENT: ${{ matrix.salt-version }}
+        SKIP_REQUIREMENTS_INSTALL: YES
+      run: |
+        nox --force-color -e tests-${{ matrix.python-version }} -- -vv tests/
+
+    - name: Upload Salt Factories Code Coverage
+      if: always()
+      shell: bash
+      env:
+        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},src
+        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-src
+        REPORT_PATH: artifacts/coverage-saltfactories.xml
+      run: |
+        if [ ! -f codecov-uploader ]; then
+            n=0
+            until [ "$n" -ge 5 ]
+            do
+            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
+                rc=$?
+                break
+            fi
+            rc=$?
+            n=$((n+1))
+            sleep 15
+            done
+        fi
+        if [ $rc -ne 0 ]; then
+            echo "Failed to download uploader"
+            exit 1
+        fi
+        if [ -f codecov-uploader ]; then
+            chmod +x codecov-uploader
+            n=0
+            until [ "$n" -ge 5 ]
+            do
+            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
+                rc=$?
+                break
+            fi
+            rc=$?
+            n=$((n+1))
+            sleep 15
+            done
+        fi
+        if [ $rc -ne 0 ]; then
+            echo "Failed to upload codecov stats"
+            exit 1
+        fi
+
+    - name: Upload Salt Factories Tests Code Coverage
+      if: always()
+      shell: bash
+      env:
+        REPORT_FLAGS: ${{ steps.codecov.outputs.flags }},tests
+        REPORT_NAME: ${{ steps.codecov.outputs.report-name }}-tests
+        REPORT_PATH: artifacts/coverage-tests.xml
+      run: |
+        if [ ! -f codecov-uploader ]; then
+            n=0
+            until [ "$n" -ge 5 ]
+            do
+            if curl --max-time 30 -L ${{ steps.codecov-info.outputs.uploader-url }} --output codecov-uploader; then
+                rc=$?
+                break
+            fi
+            rc=$?
+            n=$((n+1))
+            sleep 15
+            done
+        fi
+        if [ $rc -ne 0 ]; then
+            echo "Failed to download uploader"
+            exit 1
+        fi
+        if [ -f codecov-uploader ]; then
+            chmod +x codecov-uploader
+            n=0
+            until [ "$n" -ge 5 ]
+            do
+            if ./codecov-uploader -R $(pwd) -n "${REPORT_NAME}" -f "${REPORT_PATH}" -F "${REPORT_FLAGS}"; then
+                rc=$?
+                break
+            fi
+            rc=$?
+            n=$((n+1))
+            sleep 15
+            done
+        fi
+        if [ $rc -ne 0 ]; then
+            echo "Failed to upload codecov stats"
+            exit 1
+        fi
+
+    - name: Upload Logs
+      if: always()
+      uses: actions/upload-artifact@main
+      with:
+        name: runtests-${{ steps.codecov.outputs.report-name }}.log
+        path: artifacts/runtests-*.log
+
+
   Linux:
     runs-on: ubuntu-20.04
     needs: Pre-Commit
@@ -593,7 +752,6 @@ jobs:
       max-parallel: 16
       matrix:
         python-version:
-          - 3.5
           - 3.6
           - 3.7
           - 3.8
@@ -602,21 +760,10 @@ jobs:
           - salt~=3003.0
           - salt~=3004.0
         pytest-version:
+          - "~=6.0.0"
           - "~=6.1.0"
           - "~=6.2.0"
-          - "~=7.0.0"
-          - "~=7.1.0"
-        exclude:
-          - {"python-version": "3.5", "pytest-version": "~=6.2.0", "salt-version": "salt~=3003.0"}
-          - {"python-version": "3.5", "pytest-version": "~=7.0.0", "salt-version": "salt~=3003.0"}
-          - {"python-version": "3.5", "pytest-version": "~=7.1.0", "salt-version": "salt~=3003.0"}
-          - {"python-version": "3.6", "pytest-version": "~=7.1.0", "salt-version": "salt~=3003.0"}
-          - {"python-version": "3.10", "pytest-version": "~=6.1.0", "salt-version": "salt~=3003.0"}
-          - {"python-version": "3.5", "pytest-version": "~=6.2.0", "salt-version": "salt~=3004.0"}
-          - {"python-version": "3.5", "pytest-version": "~=7.0.0", "salt-version": "salt~=3004.0"}
-          - {"python-version": "3.5", "pytest-version": "~=7.1.0", "salt-version": "salt~=3004.0"}
-          - {"python-version": "3.6", "pytest-version": "~=7.1.0", "salt-version": "salt~=3004.0"}
-          - {"python-version": "3.10", "pytest-version": "~=6.1.0", "salt-version": "salt~=3004.0"}
+          - ">=7.0.0rc1"
 
     steps:
     - uses: actions/checkout@v2
@@ -767,6 +914,7 @@ jobs:
       - Docs
       - PyLint
       - Linux
+      - Linux_3_5
       - Windows
       - macOS
       - Linux-System-Install
